# Generated by Django 5.1.5 on 2025-02-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_task_creator_alter_task_responsible'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
