# Generated by Django 5.1.5 on 2025-02-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='responsible',
            new_name='executor',
        ),
    ]
